create table if not exists public.resenas (
    id bigint generated by default as identity primary key,
    nombre text not null,
    puntaje numeric(2, 1) not null check (puntaje >= 1 and puntaje <= 5),
    texto text not null,
    visible boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.resenas enable row level security;

drop policy if exists "Resenas visibles publicas" on public.resenas;
create policy "Resenas visibles publicas"
on public.resenas
for select
to anon
using (visible = true);

drop policy if exists "Cualquiera puede crear resenas" on public.resenas;
create policy "Cualquiera puede crear resenas"
on public.resenas
for insert
to anon
with check (
    nombre <> ''
    and texto <> ''
    and puntaje >= 1
    and puntaje <= 5
);
